import esbuild from "esbuild";
import process from "process";
import module from "module";
import esbuildSvelte from "esbuild-svelte";
import sveltePreprocess from "svelte-preprocess";
import fs from "fs";
import { exec } from "child_process";

const builtins = module.builtinModules;

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const copyCssPlugin = {
	name: 'copy-css',
	setup(build) {
		build.onEnd(() => {
			try {
				if (fs.existsSync("main.css")) {
					fs.copyFileSync("main.css", "styles.css");
					console.log("Copied main.css to styles.css successfully.");
				}
			} catch (e) {
				console.error("Failed to copy main.css to styles.css:", e);
			}
		});
	},
};

const restartObsidianPlugin = {
	name: 'restart-obsidian',
	setup(build) {
		build.onEnd(() => {
			if (prod) return;
			try {
				exec('powershell -Command "Stop-Process -Name Obsidian -ErrorAction SilentlyContinue; Start-Process \'C:\\Users\\26070\\AppData\\Local\\Obsidian\\Obsidian.exe\'"', (err) => {
					if (err) console.error("Auto-restart Obsidian failed:", err);
					else console.log("Obsidian auto-restarted after build successfully.");
				});
			} catch (e) {
				console.error("Failed to restart Obsidian:", e);
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	plugins: [
		esbuildSvelte({
			compilerOptions: { css: "injected" },
			preprocess: sveltePreprocess(),
		}),
		copyCssPlugin,
		...(prod ? [] : [restartObsidianPlugin]),
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
